<?php
class ConNguoi
{
    var $chan;
    var $tay;
    var $mat;
    var $mui;
    function an(){

    }
}
class NguoiLon extends ConNguoi
{
    var $chieucao;
    function di()
    {

    }
    function noi()
    {

    }
}
class TreCon extends ConNguoi
{
    function bo()
    {

    }
}
?>
<!-- kế thừa bắc cầu -->
<?php
class A
{
    //class A
}
class B extends A
{

}
class C extends B
{
    //class C
}
?>
<!--thuộc tính và phương thuqcs của lớp cha-->
<?php
class ParentClass
{
    function getClass(){
        return 'ParentClass';
    }
}
class ChildClass extends ParentClass{
    var $name = 'ChildClass';
    function getClass()
    {
        return 'ChildClass';
        //return parent::getClass(); // TODO: Change the autogenerated stub
    }
    function getMethod(){
        echo 'đây là phương thức ăn của lớp ' .$this->getclass() .'<br>';
    }
    function getMethodParent(){
        echo 'Đây là phương thức ăn của lớp ' .parent::getClass();
    }
}
$class = new ChildClass();
$class -> getMethod();
//kết quả:đây là phương thức ăn của lớp trẻ con
$class-> getMethodParent();
//kết quả đây là phương thức ăn của lớp class người lớn
?>