<!--1. Phương thức khởi tạo
-trong php có hỗ trợ 2 phương thức khai báo phương thức khởi tạo
cách 1: khai bóa trùng tên của 1 class(PHP version > 7x không hỗ trợ nữa)
-->
<?php
class Foo
{
//khai báo phương thức khởi tạo
    public function Foo()
    {
        echo 'class Foo được khởi tạo';
    }

}
new Foo();
//cách 2: khai báo phương thức có tên __construct()
class Fo{
    public function __construct(){
        echo 'class Fo được khởi tạo';
    }
}
new Fo();
//kết quả class fo được khởi tạo
?>
<!-- 2. phương thức hủy
-phương thức hủy trong class sẽ được gọi khi class đó đã hủy. nó thường dùng để giải phóng tài nguyên của một class và trong một class có thể có phương thức hủy
-để khai báo phương thức hủy trong class thì ta chỉ cần khai báo phương thức có name là __destruct()
-->
<?php
class Foo2{
    public function __destruct()
    {
        echo 'class Foo được hủy';
    }
}
$foo = new Foo2();
?>
<!--khi một class có đầy đủ phương thức khởi tạo và phương thức hủy-->
<?php
class two{
    public function __construct()
    {
        echo " class two khởi tạo thành công";
    }
    public function getMessage(){
        echo 'dây là class two';
    }
    public function __destruct(){
        echo 'class two được hủy';
    }
}
$two =new two();
//kết quả: class two đã được khởi tạo
$two -> getMessage();
//kết quả: đây là class two
//kết quả: clas two được hủy
?>
<!-- 3. phương thức khởi tạo và phương thức hủy trong kế thừa-->
<?php
class Bar
{
    public function  __construct(){
        echo 'class Bar duoc khoi tao';
    }
    public function __destruct(){
        echo'class Bar da duoc huy';
    }
}
class flo extends Bar{
    public function __construct() {
        echo 'class flo da duoc khoi tao';
    }
    public function __destruct()
    {
        echo 'class flow da duoc xoa';
      //  parent::__destruct(); // TODO: Change the autogenerated stub
    }
}
$flo = new flo();
//kết quả:class flo được khởi tạo
//kết quả: class flo được hủy
?>
<!--nếu muốn sử dụng được phương thức khởi tạo và phương thức hủy trong class cha thì ta chỉ cần gọi lại phương thức đó của lớp cha-->
<?php
class Ber{
    public function __construct()
    {
        echo'class Ber được khởi tạo';
    }
    public function __destruct()
    {
     echo 'class Ber được hủy';
        // TODO: Implement __destruct() method.
    }
}
class floo extends Ber{
    public function __construct(){
        //gọi phương thức khởi tạo của class cha
        parent::__construct();
        echo 'class floo được khởi tạo';
    }
    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
        echo 'class floo được hủy';
    }
}
$floo =new floo();
?>
